# Generated by Django 3.1.2 on 2021-03-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='nom',
            new_name='theme',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='date',
        ),
        migrations.AlterField(
            model_name='projet',
            name='rubrique',
            field=models.CharField(max_length=100),
        ),
    ]
