# Generated by Django 3.1.2 on 2021-05-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_auto_20210317_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='membres',
            field=models.CharField(default=5, max_length=200),
            preserve_default=False,
        ),
    ]
