# Generated by Django 3.1.2 on 2021-06-10 21:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0004_auto_20210512_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 21, 49, 45, 374445, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(upload_to='./images'),
        ),
    ]
