# Generated by Django 3.1.2 on 2021-06-10 21:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0005_auto_20210610_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 21, 50, 26, 848529, tzinfo=utc)),
        ),
    ]
