# Generated by Django 3.1.2 on 2021-06-17 16:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0006_auto_20210610_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='membres',
            new_name='initiateurs',
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='note',
            new_name='note_administrateur',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='date',
        ),
        migrations.AddField(
            model_name='projet',
            name='budget',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projet',
            name='date_de_publication',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 16, 25, 20, 145090, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='projet',
            name='note_conseiller',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
