# Generated by Django 3.1.2 on 2021-06-27 20:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0007_auto_20210617_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='date_de_publication',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 20, 0, 33, 857558, tzinfo=utc)),
        ),
    ]
