# Generated by Django 3.1.2 on 2021-06-28 23:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projets', '0008_auto_20210627_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='initiateurs',
        ),
        migrations.AddField(
            model_name='projet',
            name='initiateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_de_publication',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 23, 7, 2, 420596, tzinfo=utc)),
        ),
    ]
