# Generated by Django 3.1.2 on 2021-06-29 10:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0009_auto_20210628_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='note_administrateur',
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_de_publication',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 10, 15, 9, 927004, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projet',
            name='note_conseiller',
            field=models.IntegerField(default=0),
        ),
    ]
