# Generated by Django 3.1.2 on 2021-06-30 00:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0018_auto_20210629_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='date_de_publication',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 0, 48, 19, 702540, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
