# Generated by Django 3.1.2 on 2021-06-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubriques', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubrique',
            name='description2',
        ),
        migrations.AlterField(
            model_name='rubrique',
            name='image',
            field=models.FilePathField(path='/images'),
        ),
    ]
